gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is IGNATIUS.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "We humans live alongside POKéMON.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But enough about me.\n$"

gText_Birch_BoyOrGirl::
	.string "What did you say that\n"
	.string "your name was?$"

gText_Birch_WhatsYourName::
	.string "You look familar…\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Oh wait, it's LAUREN?\p"
	.string "Ah! I'm so sorry.\n"
	.string "How did I not recognise you!\p"
	.string "You're LAUREN, you're SAMUEL's wife.\n"
	.string "He was my best-friend.\l"
	.string "I mean, maybe he still is!\p"
	.string "I will have to ask him when you both\n"
	.string "move into your new home.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Oh, how I have missed you both!\p"
	.string "I cannot wait to see you LAUREN,\n"
	.string "send my best to SAMUEL.\l"
	.string "And to your own child too.\p"
	.string "I will see you both very soon.\n"
	.string "Have a safe journey!\p"
	.string "$"
